name: tensorflow
channels:
  - conda-forge
  - defaults
dependencies:
  - python >=3.9,<3.11
  - tensorflow==2.16.1
  - keras==3.3.3
  - pandas==2.1.1
  - ipywidgets==8.1.1
  - pooch==1.8.1
  - matplotlib==3.8.3
  - pip=24
  - pip:
      - jupyterlab==4.1.4
      - dlai-grader>=1.18.0
      - tensorflow-datasets==4.9.4



